### ISSUE TITLE
As a user, I want to see the products

### ISSUE THREAD

**Issue by tanguy-a** [quaresc/glo-2005-h19-equipe-17#7]
- [x] Web view
- [x] Python Server
- [x] Database

As a user,
I want to see the products,
In order to see I can buy.

## Web view
The user can access a page with a list of every products.

### Conditions of success
| Condition | Description |
|-|-|
| C1 | The user gets access to the products |

### Request
```
GET /products
```

### Response
```
200 HTTP OK
```

## Database
This requires the table products.

**Comment by quaresc** [comment]
Resolved with #32
