### ISSUE TITLE
As a user, I want to navigate through the website

### ISSUE THREAD

**Issue by tanguy-a** [quaresc/glo-2005-h19-equipe-17#8]
- [ ] Web view
- [ ] Python Server
- [x] Database

As a user,
I want to navigate through the website,
In order to access the different products categories.

## Web view
The user can use a navigation bar.

### Conditions of success
| Condition | Description |
|-|-|
| C1 | The user can access the different products categories |

### Request
```
GET /products/categoryName
```

### Response
```
200 HTTP OK
```

## Database
This requires the table Products.

**Comment by quaresc** [comment]
Resolved with #32
